### ISSUE TITLE
Tooltips do not work for Toolbar

### ISSUE THREAD

**Issue by kczx3** [flipeador/Library-AutoHotkey#1]
In my experiments, Tooltips do not appear to display for a Toolbar with the TBSTYLE_TOOLTIPS unless TB_SETMAXTEXTROWS is called with 0 for the wParam.

Additionally, the Text does not appropriately get assigned to a button unless the Identifier is unique to each added button.

**Comment by flipeador** [comment]
>  Tooltips do not appear [...]

Does the same thing happen in this version?:
https://github.com/flipeador/Library-AutoHotkey/tree/master/gui/Toolbar
See the example. I only took a few hours to rewrite the code, surely there are things to improve.

> the Text does not appropriately get assigned to a button unless the Identifier is unique to each added button

In the previous version of the class, I put the identifier as something unimportant, but I think it is important to give a unique identifier to each button.
Some messages work with the identifier, and if a unique one is not established for each button, it is not possible to reference them.

**Comment by kczx3** [comment]
Actually, it worked before.  The Toolbar just requires the LIST style.

I hope you didn't rewrite this because of my comment.

**Comment by flipeador** [comment]
I was going to rewrite it anyway, I did not like the previous version. I'm glad it works.
